import prisma from '../src/config/db';

const categories = [
  { name: 'frontend' },
  { name: 'backend' },
  { name: 'database' },
  { name: 'express.js' },
  { name: 'redis' },
  { name: 'kafka' },
  { name: 'nginx' },
  { name: 'docker' },
  { name: 'sdk' },
  { name: 'api' },
  { name: 'rest' },
  { name: 'graphql' },
  { name: 'grpc' },
  { name: 'websocket' },
  { name: 'microservices' },
  { name: 'monolith' },
  { name: 'serverless' },
  { name: 'devops' },
  { name: 'ci-cd' },
  { name: 'kubernetes' },
  { name: 'aws' },
  { name: 'azure' },
  { name: 'gcp' },
  { name: 'cloud' },
  { name: 'terraform' },
  { name: 'ansible' },
  { name: 'linux' },
  { name: 'bash' },
  { name: 'git' },
  { name: 'github' },
  { name: 'gitlab' },
  { name: 'open-source' },
  { name: 'javascript' },
  { name: 'typescript' },
  { name: 'python' },
  { name: 'java' },
  { name: 'go' },
  { name: 'rust' },
  { name: 'c++' },
  { name: 'c#' },
  { name: 'php' },
  { name: 'ruby' },
  { name: 'react' },
  { name: 'vue' },
  { name: 'angular' },
  { name: 'next.js' },
  { name: 'nuxt.js' },
  { name: 'svelte' },
  { name: 'tailwindcss' },
  { name: 'css' },
  { name: 'html' },
  { name: 'node.js' },
  { name: 'deno' },
  { name: 'bun' },
  { name: 'spring-boot' },
  { name: 'django' },
  { name: 'fastapi' },
  { name: 'laravel' },
  { name: 'rails' },
  { name: 'postgresql' },
  { name: 'mysql' },
  { name: 'mongodb' },
  { name: 'sqlite' },
  { name: 'cassandra' },
  { name: 'elasticsearch' },
  { name: 'firebase' },
  { name: 'orm' },
  { name: 'prisma' },
  { name: 'sequelize' },
  { name: 'typeorm' },
  { name: 'mongoose' },
  { name: 'rabbitmq' },
  { name: 'mqtt' },
  { name: 'websockets' },
  { name: 'sse' },
  { name: 'long-polling' },
  { name: 'jwt' },
  { name: 'oauth' },
  { name: 'authentication' },
  { name: 'authorization' },
  { name: 'encryption' },
  { name: 'security' },
  { name: 'cors' },
  { name: 'testing' },
  { name: 'unit-testing' },
  { name: 'e2e-testing' },
  { name: 'jest' },
  { name: 'vitest' },
  { name: 'cypress' },
  { name: 'architecture' },
  { name: 'design-patterns' },
  { name: 'clean-code' },
  { name: 'solid' },
  { name: 'ddd' },
  { name: 'tdd' },
  { name: 'cqrs' },
  { name: 'event-driven' },
  { name: 'performance' },
  { name: 'caching' },
  { name: 'load-balancing' },
  { name: 'rate-limiting' },
  { name: 'scalability' },
  { name: 'monitoring' },
  { name: 'logging' },
  { name: 'observability' },
  { name: 'tracing' },
  { name: 'prometheus' },
  { name: 'grafana' },
  { name: 'machine-learning' },
  { name: 'ai' },
  { name: 'llm' },
  
  { name: 'data-structures' },
  { name: 'algorithms' },
  { name: 'system-design' },
  { name: 'debugging' },
  { name: 'json' },
];
async function main() {
  for (const category of categories) {
    await prisma.category.upsert({
      where: { name: category.name },
      update: {},
      create: category,
    });
  }
  console.log('Categories seeded successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
